void DRAW_DEBUG_SPHERE(float x, float y, float z, float radius); 
uint CREATE_USER_3D_MARKER(float x, float y, float z); 
void REMOVE_USER_3D_MARKER(uint marker);
void SET_SPRITE_HDR_MULTIPLIER(float multiplier);
STREAM_CUTSCENE
REMOVE_ALL_SCRIPT_FIRES
SET_SCRIPT_FIRE_AUDIO
ADD_EXPLOSION_WITH_DIRECTION
void SET_CHAR_WEAPON_SKILL(Ped ped, int skill);
GET_CLOSEST_STRAIGHT_ROAD
GET_PARKING_NODE_IN_AREA
void GRAB_ENTITY_ON_ROPE_FOR_OBJECT(Object obj, int *, int *, int *); 
void GET_ROPE_HEIGHT_FOR_OBJECT(Object obj, float *height);
IS_OBJECT_IN_AREA_2D
RELEASE_ENTITY_FROM_ROPE_FOR_OBJECT
IS_OBJECT_IN_ANGLED_AREA_2D
ATTACH_OBJECT_TO_PED_PHYSICALLY
SET_ROPE_HEIGHT_FOR_OBJECT
ATTACH_OBJECT_TO_OBJECT_PHYSICALLY
IS_CAR_IN_ANGLED_AREA_2D
IS_CAR_IN_ANGLED_AREA_3D
ATTACH_CAR_TO_CAR_PHYSICALLY
GET_VEHICLE_CLASS 
ATTACH_CAR_TO_OBJECT_PHYSICALLY
IS_CAR_STOPPED_IN_AREA_2D
CREATE_CAR_GENERATOR_WITH_PLATE 
SET_ALTERNATIVE_HEAD_FOR_PED_QUEUE
TASK_FOLLOW_PATROL_ROUTE
TASK_SIT_DOWN_PLAY_ANIM
TASK_CHAR_SLIDE_TO_COORD_AND_PLAY_ANIM_HDG_RATE
TASK_SPACE_SHIP_GO_TO_COORD
GET_SEQUENCE_PROGRESS_RECURSIVE
ADD_PED_QUEUE
REMOVE_PED_QUEUE
TASK_SAY
SET_PED_QUEUE_MEMBERSHIP_LIST
SET_EVENT_PRECEDENCE
CLEAR_EVENT_PRECEDENCE
END_PED_QUEUE_MEMBERSHIP_LIST
TASK_JETPACK
BEGIN_PED_QUEUE_MEMBERSHIP_LIST
GET_PED_AT_HEAD_OF_QUEUE
GET_NEEDED_PLAYER_CASH_FOR_LEVEL
TAKE_REMOTE_CONTROL_OF_CAR
MAKE_ROOM_IN_PLAYER_GANG_FOR_MISSION_PEDS
USE_DETONATOR
GIVE_PLAYER_HELMET
boolean IS_PLAYER_IN_INFO_ZONE(int player, int zoneid);
GET_REMOTE_CONTROLLED_CAR
SET_HEADING_FOR_ATTACHED_PLAYER
REMOVE_RC_BUGGY
IS_ATTACHED_PLAYER_HEADING_ACHIEVED
IS_PLAYER_IN_SHORTCUT_TAXI
DO_WEAPON_STUFF_AT_START_OF_2P_GAME
GIVE_REMOTE_CONTROLLED_MODEL_TO_PLAYER
void SET_ROOM_FOR_DUMMY_CHAR_BY_KEY(Ped dummy, int key);
void CLEAR_ROOM_FOR_DUMMY_CHAR(Ped ped);
CREATE_DUMMY_CHAR
void SET_ROOM_FOR_DUMMY_CHAR_BY_NAME(Ped ped, char *roomname);
void GET_KEY_FOR_DUMMY_CHAR_IN_ROOM(Ped ped, int *room);
ATTACH_PED_TO_CAR2
ATTACH_PED_TO_WORLD_PHYSICALLY
DELETE_DUMMY_CHAR
GET_CHAR_AREA_VISIBLE
SET_CHAR_DEFENSIVE_AREA_ATTACHED_TO_CAR
GET_INTERIOR_FROM_DUMMY_CHAR
GET_CHAR_ANIM_EVENT_TIME
boolean HAS_RELOADED_WITH_MOTION_CONTROL(ScriptAny, ScriptAny);
GET_MOTION_SENSOR_VALUES
GET_MOTION_CONTROLS_ENABLED
GET_PAD_ORIENTATION
void SET_UP_TRIP_SKIP_FOR_SPECIFIC_VEHICLE(float, float, float, float, Vehicle veh);
SET_UP_TRIP_SKIP_TO_BE_FINISHED_BY_SCRIPT
SET_UP_TRIP_SKIP_AFTER_MISSION
CLEAR_UP_TRIP_SKIP
SET_UP_TRIP_SKIP_FOR_VEHICLE_FINISHED_BY_SCRIPT
SET_UP_TRIP_SKIP
SET_AREA_NAME
GET_BLIP_INFO_ID_POSITION
RENDER_LOADING_CLOCK
RENDER_RADIOHUD_SPRITE_IN_MOBILE_PHONE
CAN_RENDER_RADIOHUD_SPRITE_IN_MOBILE_PHONE
RENDER_RADIOHUD_SPRITE_IN_LOBBY
TURN_ON_RADIOHUD_IN_LOBBY
DEBUG_ON
void DEBUG_OFF(void);
void SET_DEBUG_TEXT_VISIBLE(ScriptAny);
void SCRIPT_ASSERT(ScriptAny);
void OPEN_DEBUG_FILE(void);
void CLOSE_DEBUG_FILE(void);
void SAVE_INT_TO_DEBUG_FILE(ScriptAny);
void SAVE_FLOAT_TO_DEBUG_FILE(ScriptAny);
void SAVE_NEWLINE_TO_DEBUG_FILE(void);
void SAVE_STRING_TO_DEBUG_FILE(ScriptAny);
GET_MODEL_NAME_OF_CAR_FOR_DEBUG_ONLY
ScriptAny GET_MODEL_NAME_FOR_DEBUG(ScriptAny);
GET_ROOM_NAME_FROM_CHAR_DEBUG
void INIT_DEBUG_WIDGETS(void);
ScriptAny CREATE_WIDGET_GROUP(ScriptAny);
void END_WIDGET_GROUP(void);
ScriptAny ADD_WIDGET_SLIDER(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny ADD_WIDGET_FLOAT_SLIDER(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny ADD_WIDGET_READ_ONLY(ScriptAny, ScriptAny);
ScriptAny ADD_WIDGET_FLOAT_READ_ONLY(ScriptAny, ScriptAny);
ScriptAny ADD_WIDGET_TOGGLE(ScriptAny, ScriptAny);
ScriptAny ADD_WIDGET_STRING(ScriptAny);
void DELETE_WIDGET_GROUP(ScriptAny);
void DELETE_WIDGET(ScriptAny);
void ScriptAny DOES_WIDGET_GROUP_EXIST(ScriptAny);
void GET_CONSOLE_COMMAND
void RESET_CONSOLE_COMMAND
voidvoid START_NEW_WIDGET_COMBO(void);
void ADD_TO_WIDGET_COMBO(ScriptAny);
ScriptAny FINISH_WIDGET_COMBO(ScriptAny, ScriptAny);
ScriptAny ADD_TEXT_WIDGET(ScriptAny);
ScriptAny GET_CONTENTS_OF_TEXT_WIDGET(ScriptAny);
void SET_CONTENTS_OF_TEXT_WIDGET(ScriptAny, ScriptAny);
ACTIVATE_VECTOR_MAP
SET_ALL_PEDS_SPAWNED_ARE_COPS
GET_NETWORK_RESTART_NODE_DEBUG
TAKE_SCREEN_SHOT
DISABLE_DEBUG_CAM_AND_PLAYER_WARPING
PRINT_MISSION_DESCRIPTION
GET_NAME_OF_SCRIPT_TO_AUTOMATICALLY_START
IS_CAM_COLLIDING
GET_MOBILE_PHONE_ROTATION
GET_MOBILE_PHONE_POSITION
WAITUNWARPED
WAITUNPAUSED
PRINTFLOAT2
PRINTINT2
BREAKPOINT
int GET_LATEST_CONSOLE_COMMAND(void);
RESET_LATEST_CONSOLE_COMMAND
int GET_CONSOLE_COMMAND_TOKEN(void);
GET_NUM_CONSOLE_COMMAND_TOKENS
START_PROFILE_TIMER
STOP_PROFILE_TIMER
SET_CHAR_NAME_DEBUG
void UPDATE_NETWORK_STATISTICS(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
void REGISTER_MULTIPLAYER_GAME_WIN(ScriptAny, ScriptAny);
void REGISTER_NETWORK_BEST_GAME_SCORES(ScriptAny, ScriptAny, ScriptAny);
ScriptAny GET_GAMER_NETWORK_SCORE(ScriptAny, ScriptAny, ScriptAny);
RESET_HEALTH_PICKUP_NETWORK_REGEN_TIME
void SET_HEALTH_PICKUP_NETWORK_REGEN_TIME(ScriptAny);
void SET_PLAYERS_DROP_MONEY_IN_NETWORK_GAME(ScriptAny);
RESET_ARMOUR_PICKUP_NETWORK_REGEN_TIME
void SET_WEAPON_PICKUP_NETWORK_REGEN_TIME(ScriptAny, ScriptAny);
void SET_ARMOUR_PICKUP_NETWORK_REGEN_TIME(ScriptAny);
SET_MONEY_PICKUP_NETWORK_REGEN_TIME
RESET_WEAPON_PICKUP_NETWORK_REGEN_TIME
RESET_MONEY_PICKUP_NETWORK_REGEN_TIME
uint GET_PLAYER_COLOUR(int Player);
void GET_PLAYER_RGB_COLOUR(int Player, int *r, int *g, int *b);
int GET_PLAYER_TEAM(int Player);
void SET_PLAYER_TEAM(int Player, int);
ScriptAny GET_NO_OF_PLAYERS_IN_TEAM(ScriptAny);
ScriptAny GET_PLAYER_NAME(ScriptAny);
SET_PLAYER_COLOUR
IS_2PLAYER_GAME_GOING_ON
ScriptAny HAS_GAMER_CHANGED_NETWORK_MODEL_SETTINGS(void);
FORCE_NET_PLAYER_INVISIBLE
PLAYER_HAS_FLASHING_STAR_AFTER_OFFENCE
SET_PLAYERS_CAN_BE_IN_SEPARATE_CARS
void SET_PLAYER_CONTROL_FOR_NETWORK(ScriptAny, ScriptAny, ScriptAny);
RELEASE_TWO_PLAYER_DISTANCE
void ALLOW_LOCKON_TO_FRIENDLY_PLAYERS(ScriptAny, ScriptAny);
HAS_PLAYER_RANK_BEEN_UPGRADED
int MP_GET_AMOUNT_OF_VARIATION_COMPONENT(Ped ped, int componentid);
int MP_GET_AMOUNT_OF_ANCHOR_POINTS(Ped ped, int id);
int MP_GET_VARIATION_SETUP(Ped ped, int, int, int, int);
int MP_GET_PROP_SETUP(Ped ped, int, int, int, int);
int MP_GET_PREFERENCE_VALUE(int prefid);
void MP_SET_PREFERENCE_VALUE(int prefid, int value);
GET_OVERRIDE_NO_SPRINTING_ON_PHONE_IN_MULTIPLAYER
void SET_OVERRIDE_NO_SPRINTING_ON_PHONE_IN_MULTIPLAYER(ScriptAny);
SET_MULTIPLAYER_BRIEF
void UPDATE_NETWORK_RELATIVE_SCORE(ScriptAny, ScriptAny, ScriptAny);
void UNOBFUSCATE_INT(int count, int *val);
boolean NETWORK_CHANGE_GAME_MODE_PENDING(void);
void SET_RICH_PRESENCE_TEMPLATEFILTER(void);
int NETWORK_GET_HOST_MATCH_PROGRESS(int host);
void GET_PED_FROM_NETWORK_ID(int id, Ped *ped);
void GET_NETWORK_ID_FROM_OBJECT(Object obj, int *id);
boolean NETWORK_RETURN_TO_RENDEZVOUS_SUCCEEDED(void);
void SET_RICH_PRESENCE_TEMPLATESP2(int);
boolean NETWORK_JOIN_SUMMONS(void);
boolean NETWORK_IS_COMMON_EPISODE(int id);
void SET_RICH_PRESENCE_TEMPLATEMP3(int, int);
void FIND_NETWORK_RESTART_POINT(ScriptAny, ScriptAny, ScriptAny);
void SET_PED_EXISTS_ON_ALL_MACHINES(Ped ped, boolean exists);
ScriptAny GET_HOST_ID(void);
void NETWORK_SET_SCRIPT_LOBBY_STATE(ScriptAny);
ScriptAny REQUEST_CONTROL_OF_NETWORK_ID(ScriptAny);
ScriptAny NETWORK_SET_PLAYER_MUTED(ScriptAny, ScriptAny);
ScriptAny NETWORK_IS_PLAYER_MUTED_BY_ME(ScriptAny);
ScriptAny CALCULATE_CHECKSUM(ScriptAny, ScriptAny);
void NETWORK_START_EXTENDED_SEARCH(ScriptAny);
ScriptAny NETWORK_SEND_TEXT_CHAT(ScriptAny, ScriptAny);
ScriptAny GET_START_FROM_FILTER_MENU(void);
ScriptAny NETWORK_HOST_GAME_PENDING(void);
int NETWORK_GET_HOST_AVERAGE_RANK(int host);
ScriptAny NETWORK_IS_INVITEE_ONLINE(void);
ScriptAny IS_PARTY_MODE(void);
ScriptAny NETWORK_IS_FIND_RESULT_VALID(ScriptAny);
void SET_RICH_PRESENCE_TEMPLATEMP2(ScriptAny);
void SET_START_FROM_FILTER_MENU(ScriptAny);
void NETWORK_CHANGE_EXTENDED_GAME_CONFIG(ScriptAny);
ScriptAny GET_SERVER_ID(void);
void NETWORK_SHOW_FRIEND_PROFILE_UI(ScriptAny);
ScriptAny NETWORK_IS_RENDEZVOUS(void);
ScriptAny GET_DESTROYER_OF_NETWORK_ID(ScriptAny, ScriptAny);
void SET_FILTER_MENU_ON(ScriptAny);
ADD_NETWORK_RESTART
TELEPORT_NETWORK_PLAYER
ScriptAny NETWORK_PLAYER_HAS_DIED_RECENTLY(ScriptAny);
void NETWORK_FIND_GAME(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny NETWORK_FIND_GAME_PENDING(void);
ScriptAny NETWORK_GET_NUMBER_OF_GAMES(void);
ScriptAny NETWORK_START_SESSION(void);
SET_CAR_STOP_CLONING
void SET_SERVER_ID(ScriptAny);
void SET_NETWORK_VEHICLE_RESPOT_TIMER(ScriptAny, ScriptAny);
ScriptAny NETWORK_HOST_GAME_E1(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
NETWORK_HOST_GAME_CNC
ScriptAny NETWORK_HOST_RENDEZVOUS_E1(ScriptAny, ScriptAny, ScriptAny);
ScriptAny NETWORK_IS_OPERATION_PENDING(void);
ScriptAny NETWORK_HOST_GAME_SUCCEEDED(void);
ScriptAny GET_NETWORK_JOIN_FAIL(void);
ScriptAny NETWORK_IS_TVT(void);
void SHUTDOWN_AND_LAUNCH_NETWORK_GAME(ScriptAny);
ScriptAny DOES_OBJECT_EXIST_WITH_NETWORK_ID(ScriptAny);
void NETWORK_SET_TEXT_CHAT_RECIPIENTS(ScriptAny);
ScriptAny GET_HOST_MATCH_ON(void);
ScriptAny NETWORK_IS_ROCKSTART_SESSION_ID_VALID(void);
ScriptAny GET_FILTER_MENU_ON(void);
ScriptAny NETWORK_START_SESSION_PENDING(void);
ScriptAny GET_GFWL_HAS_SAFE_HOUSE(void);
void GET_VEHICLE_FROM_NETWORK_ID(ScriptAny, ScriptAny);
ScriptAny NETWORK_IS_RENDEZVOUS_HOST(void);
void USE_PLAYER_COLOUR_INSTEAD_OF_TEAM_COLOUR(ScriptAny);
SET_NETWORK_ID_STOP_CLONING_FOR_ENEMIES
void SET_RICH_PRESENCE_TEMPLATEPARTY(void);
ScriptAny NETWORK_SET_LOCAL_PLAYER_IS_TYPING(ScriptAny);
void SET_HOST_MATCH_ON(ScriptAny);
void OBFUSCATE_INT(ScriptAny, ScriptAny);
ScriptAny NETWORK_IS_PLAYER_BLOCKED_BY_ME(ScriptAny);
void SET_RICH_PRESENCE_TEMPLATELOBBY(ScriptAny);
void SET_NETWORK_ID_STOP_CLONING(ScriptAny, ScriptAny);
ScriptAny NETWORK_CHECK_INVITE_ARRIVAL(void);
void NETWORK_KICK_PLAYER(ScriptAny, ScriptAny);
void RESERVE_NETWORK_MISSION_OBJECTS_FOR_HOST(ScriptAny);
void LAUNCH_LOCAL_PLAYER_IN_NETWORK_GAME(void);
SET_IGNORE_SERVER_UPDATE
void RESURRECT_NETWORK_PLAYER(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
void GET_NETWORK_ID_FROM_PED(ScriptAny, ScriptAny);
IS_OBJECT_ON_PLAYER_MACHINE
void SET_ONLINE_LAN(ScriptAny);
ScriptAny GET_LOCAL_GAMERLEVEL_FROM_PROFILESETTINGS(void);
ScriptAny IS_NETWORK_PLAYER_ACTIVE(ScriptAny);
ScriptAny CAN_REGISTER_MISSION_PED(void);
ScriptAny NETWORK_GET_FRIEND_NAME(ScriptAny);
ScriptAny NETWORK_CHANGE_GAME_MODE_SUCCEEDED(void);
void CLEAR_SCRIPT_ARRAY_FROM_SCRATCHPAD(ScriptAny);
ScriptAny IS_OUR_PLAYER_HIGHER_PRIORITY_FOR_CAR_GENERATION(ScriptAny);
SET_TEAM_COLOUR
void NETWORK_CLEAR_INVITE_ARRIVAL(void);
ScriptAny RESTORE_SCRIPT_VALUES_FOR_NETWORK_GAME(ScriptAny);
ScriptAny NETWORK_JOIN_GAME(ScriptAny);
NETWORK_JOIN_GAME_CNC
ScriptAny NETWORK_JOIN_GAME_PENDING(void);
ScriptAny NETWORK_JOIN_GAME_SUCCEEDED(void);
NETWORK_GET_HOST_NAME
ScriptAny NETWORK_IS_NETWORK_AVAILABLE(void);
NETWORK_GET_HEALTH_RETICULE_OPTION
ScriptAny NETWORK_END_SESSION_PENDING(void);
ScriptAny NETWORK_HAVE_ONLINE_PRIVILEGES(void);
void SET_NETWORK_PLAYER_AS_VIP(ScriptAny, ScriptAny);
void SET_NETWORK_ID_EXISTS_ON_ALL_MACHINES(ScriptAny, ScriptAny);
HAS_NET_ID_BEEN_CLONED
ScriptAny NETWORK_CLEAR_SUMMONS(void);
ScriptAny DOES_GAME_CODE_WANT_TO_LEAVE_NETWORK_SESSION(void);
void NETWORK_FINISH_EXTENDED_SEARCH(void);
void SET_RICH_PRESENCE_TEMPLATESP1(ScriptAny, ScriptAny, ScriptAny);
REGISTER_MOD
SET_OBJECT_STOP_CLONING
ScriptAny NETWORK_IS_FRIEND_IN_SAME_TITLE(ScriptAny);
GET_NETWORK_PLAYER_VIP
ScriptAny NETWORK_IS_SESSION_ADVERTISE(void);
ScriptAny HAS_CONTROL_OF_NETWORK_ID(ScriptAny);
ScriptAny NETWORK_INVITE_FRIEND(ScriptAny, ScriptAny);
ScriptAny NETWORK_DID_INVITE_FRIEND(ScriptAny);
void NETWORK_VERIFY_USER_STRING(ScriptAny);
ScriptAny IS_OBJECT_REASSIGNMENT_IN_PROGRESS(void);
ScriptAny NETWORK_GET_MAX_SLOTS(void);
ScriptAny DOES_VEHICLE_EXIST_WITH_NETWORK_ID(ScriptAny);
ScriptAny NETWORK_GET_UNACCEPTED_INVITE_EPISODE(ScriptAny);
void NETWORK_SET_LAN_SESSION(ScriptAny);
CAN_REGISTER_MISSION_ENTITIES
ScriptAny IS_THIS_MACHINE_THE_SERVER(void);
void SET_CELLPHONE_RANKED(ScriptAny);
void SET_IN_MP_TUTORIAL(ScriptAny);
void NETWORK_SET_FRIENDLY_FIRE_OPTION(ScriptAny);
ScriptAny GET_PLAYER_RANK_LEVEL_DURING_MP(ScriptAny);
ScriptAny NETWORK_STORE_SINGLE_PLAYER_GAME(void);
ScriptAny NETWORK_GET_MET_PLAYER_NAME(ScriptAny);
void SAVE_SCRIPT_ARRAY_IN_SCRATCHPAD(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny NETWORK_GET_NUM_UNACCEPTED_INVITES(void);
void SET_RETURN_TO_FILTER_MENU(ScriptAny);
void RESERVE_NETWORK_MISSION_VEHICLES_FOR_HOST(ScriptAny);
void SET_MSG_FOR_LOADING_SCREEN(ScriptAny);
SET_PED_STOP_CLONING
ScriptAny FIND_NETWORK_KILLER_OF_PLAYER(ScriptAny);
ScriptAny NETWORK_GET_PLAYER_ID_OF_NEXT_TEXT_CHAT(void);
void SET_GFWL_HAS_SAFE_HOUSE(ScriptAny);
void RESERVE_NETWORK_MISSION_OBJECTS(ScriptAny);
void RESERVE_NETWORK_MISSION_PEDS(ScriptAny);
void GET_OBJECT_FROM_NETWORK_ID(ScriptAny, ScriptAny);
ScriptAny NETWORK_END_SESSION(void);
ScriptAny NETWORK_IS_FRIEND_ONLINE(ScriptAny);
void GET_NETWORK_ID_FROM_VEHICLE(ScriptAny, ScriptAny);
ScriptAny NETWORK_GET_SERVER_NAME(void);
IS_IN_MP_TUTORIAL
SET_OBJECT_EXISTS_ON_ALL_MACHINES
READ_LOBBY_PREFERENCE
void NETWORK_SET_HEALTH_RETICULE_OPTION(ScriptAny);
GET_CAMERA_FROM_NETWORK_ID
ScriptAny GET_RETURN_TO_FILTER_MENU(void);
ScriptAny NETWORK_HAS_STRICT_NAT(void);
void RESERVE_NETWORK_MISSION_PEDS_FOR_HOST(ScriptAny);
void SET_RICH_PRESENCE_TEMPLATEMP5(ScriptAny, ScriptAny, ScriptAny);
ScriptAny DOES_PED_EXIST_WITH_NETWORK_ID(ScriptAny);
void GET_TEAM_RGB_COLOUR(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
REMOVE_ALL_NETWORK_RESTART_POINTS
ScriptAny NETWORK_AM_I_MUTED_BY_PLAYER(ScriptAny);
ScriptAny NETWORK_GET_FRIEND_COUNT(void);
void SET_SYNC_WEATHER_AND_GAME_TIME(ScriptAny);
void SET_NETWORK_JOIN_FAIL(ScriptAny);
ScriptAny NETWORK_RESULT_MATCHES_SEARCH_CRITERIA(ScriptAny);
void NETWORK_SHOW_PLAYER_PROFILE_UI(ScriptAny);
ScriptAny NETWORK_GET_NUM_OPEN_PUBLIC_SLOTS(void);
SEND_HOST_BROADCAST_VARIABLES_NOW
ScriptAny CAN_REGISTER_MISSION_OBJECT(void);
ScriptAny IS_SPHERE_VISIBLE_TO_ANOTHER_MACHINE(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny NETWORK_GET_UNACCEPTED_INVITE_GAME_MODE(ScriptAny);
void GET_NETWORK_TIMER(ScriptAny);
ScriptAny NETWORK_GET_NUM_PARTY_MEMBERS(void);
void SET_THIS_MACHINE_RUNNING_SERVER_SCRIPT(ScriptAny);
void SET_IN_SPECTATOR_MODE(ScriptAny);
void NETWORK_SHOW_MET_PLAYER_FEEDBACK_UI(ScriptAny);
IS_CHAR_ON_PLAYER_MACHINE
ScriptAny NETWORK_SET_SESSION_INVITABLE(ScriptAny);
void SET_IK_DISABLED_FOR_NETWORK_PLAYER(ScriptAny, ScriptAny);
void REGISTER_KILL_IN_MULTIPLAYER_GAME(ScriptAny, ScriptAny, ScriptAny);
ScriptAny IS_DAMAGE_TRACKER_ACTIVE_ON_NETWORK_ID(ScriptAny);
ScriptAny NETWORK_EXPAND_TO_32_PLAYERS(void);
ScriptAny NETWORK_LEAVE_GAME(void);
void OBFUSCATE_INT_ARRAY(ScriptAny, ScriptAny);
void SET_GFWL_IS_RETURNING_TO_SINGLE_PLAYER(ScriptAny);
ScriptAny CAN_REGISTER_MISSION_VEHICLE(void);
void NETWORK_SET_TALKER_FOCUS(ScriptAny);
IS_NETWORK_CONNECTED
ScriptAny PLAYER_WANTS_TO_JOIN_NETWORK_GAME(ScriptAny);
void RESERVE_NETWORK_MISSION_VEHICLES(ScriptAny);
void STORE_SCRIPT_VALUES_FOR_NETWORK_GAME(ScriptAny);
ScriptAny LOCAL_PLAYER_IS_READY_TO_START_PLAYING(void);
ScriptAny NETWORK_RETURN_TO_RENDEZVOUS_PENDING(void);
void STOP_SYNCING_SCRIPT_ANIMATIONS(ScriptAny);
WRITE_LOBBY_PREFERENCE
ScriptAny NETWORK_IS_PLAYER_TALKING(ScriptAny);
ScriptAny NETWORK_IS_SESSION_INVITABLE(void);
int NETWORK_GET_HOST_LATENCY(int host);
ScriptAny NETWORK_GET_LAN_SESSION(void);
ScriptAny IS_NETWORK_GAME_PENDING(void);
void SEND_CLIENT_BROADCAST_VARIABLES_NOW(void);
ScriptAny NETWORK_CHANGE_GAME_MODE(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
NETWORK_GET_FRIENDLY_FIRE_OPTION
void REGISTER_CLIENT_BROADCAST_VARIABLES(ScriptAny, ScriptAny, ScriptAny);
void NETWORK_STORE_GAME_CONFIG(ScriptAny);
ScriptAny NETWORK_RESTORE_GAME_CONFIG(ScriptAny);
void NETWORK_SET_MATCH_PROGRESS(ScriptAny);
ScriptAny NETWORK_LEAVE_GAME_PENDING(void);
ScriptAny NETWORK_IS_BEING_KICKED(void);
ScriptAny NETWORK_PLAYER_HAS_COMM_PRIVS(void);
ScriptAny IS_NETWORK_SESSION(void);
ScriptAny GET_ONLINE_LAN(void);
void ACTIVATE_DAMAGE_TRACKER_ON_NETWORK_ID(ScriptAny, ScriptAny);
SET_CAR_EXISTS_ON_ALL_MACHINES
char * NETWORK_GET_HOST_SERVER_NAME(int host);
GET_SAFE_LOCAL_RESTART_COORDS
ScriptAny NETWORK_STRING_VERIFY_SUCCEEDED(void);
void NETWORK_SET_TALKER_PROXIMITY(ScriptAny);
ScriptAny NETWORK_SET_SERVER_NAME(ScriptAny);
ScriptAny NETWORK_STRING_VERIFY_PENDING(void);
ScriptAny NETWORK_GET_RENDEZVOUS_HOST_PLAYER_ID(void);
ScriptAny NETWORK_ADVERTISE_SESSION(ScriptAny);
ScriptAny HAS_NETWORK_PLAYER_LEFT_GAME(ScriptAny);
void SET_PLAYER_AS_DAMAGED_PLAYER(ScriptAny, ScriptAny, ScriptAny);
void SET_NETWORK_ID_CAN_MIGRATE(ScriptAny, ScriptAny);
void SET_RICH_PRESENCE(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
IS_VEHICLE_ON_PLAYER_MACHINE
ScriptAny NETWORK_START_SESSION_SUCCEEDED(void);
void RESTORE_SCRIPT_ARRAY_FROM_SCRATCHPAD(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
void UNOBFUSCATE_INT_ARRAY(ScriptAny, ScriptAny);
ScriptAny NETWORK_PLAYER_HAS_HEADSET(ScriptAny);
void DISPLAY_PLAYER_NAMES(ScriptAny);
ScriptAny GET_GFWL_IS_RETURNING_TO_SINGLE_PLAYER(void);
ScriptAny NETWORK_HAVE_ACCEPTED_INVITE(void);
ScriptAny NETWORK_GET_GAME_MODE(void);
GET_TEAM_COLOUR
void SET_RICH_PRESENCE_TEMPLATEMP6(ScriptAny, ScriptAny, ScriptAny);
NETWORK_SHOW_PLAYER_FEEDBACK_UI
ScriptAny NETWORK_GET_NUM_UNFILLED_RESERVATIONS(void);
ScriptAny NETWORK_GET_MAX_PRIVATE_SLOTS(void);
NETWORK_GET_TEAM_OPTION
ScriptAny NETWORK_AM_I_BLOCKED_BY_PLAYER(ScriptAny);
ScriptAny GET_CELLPHONE_RANKED(void);
ScriptAny NETWORK_HAVE_SUMMONS(void);
void NETWORK_SHOW_MET_PLAYER_PROFILE_UI(ScriptAny);
ScriptAny NETWORK_RETURN_TO_RENDEZVOUS(void);
ScriptAny NETWORK_ACCEPT_INVITE(ScriptAny);
NETWORK_SET_LOCAL_PLAYER_CAN_TALK
ScriptAny NETWORK_LIMIT_TO_16_PLAYERS(void);
ScriptAny NETWORK_IS_FIND_RESULT_UPDATED(ScriptAny);
void SHUTDOWN_AND_LAUNCH_SINGLE_PLAYER_GAME(void);
ScriptAny STORE_DAMAGE_TRACKER_FOR_NETWORK_PLAYER(ScriptAny, ScriptAny, ScriptAny);
ScriptAny HOW_LONG_HAS_NETWORK_PLAYER_BEEN_DEAD_FOR(ScriptAny);
ScriptAny NETWORK_PLAYER_HAS_KEYBOARD(ScriptAny);
ScriptAny NETWORK_GET_NEXT_TEXT_CHAT(void);
NETWORK_IS_LINK_CONNECTED
ScriptAny IS_NETWORK_GAME_RUNNING(void);
void REGISTER_HOST_BROADCAST_VARIABLES(ScriptAny, ScriptAny, ScriptAny);
ScriptAny NETWORK_GET_NUM_PLAYERS_MET(void);
ScriptAny DOES_PLAYER_HAVE_CONTROL_OF_NETWORK_ID(ScriptAny, ScriptAny);
ScriptAny NETWORK_ALL_PARTY_MEMBERS_PRESENT(void);
void NETWORK_SET_TEAM_ONLY_CHAT(ScriptAny);
NETWORK_DISPLAY_HOST_GAMER_CARD
GET_LCPD_COP_SCORE
SET_LCPD_COP_SCORE
GET_LCPD_CRIMINAL_SCORE
SET_LCPD_CRIMINAL_SCORE
DISPLAY_PLAYER_ICONS
IS_NETWORK_PLAYER_VISIBLE
void SET_DISPLAY_PLAYER_NAME_AND_ICON(ScriptAny, ScriptAny);
GET_PLAYER_LCPD_SCORE
UPDATE_PLAYER_LCPD_SCORE
SET_NETWORK_VISIBILITY
GET_LAST_TIME_NETWORK_ID_DAMAGED
void SET_NETWORK_PED_USING_PARACHUTE(ScriptAny);
CLAN_IS_PENDING
ScriptAny GET_ONLINE_SCORE(ScriptAny);
void SET_ONLINE_SCORE(ScriptAny, ScriptAny);
ScriptAny IS_LCPD_DATA_VALID(void);
LCPD_FIRST_TIME
LCPD_HAS_BEEN_CONFIGURED
START_KILL_TRACKING
STOP_KILL_TRACKING
GET_KILL_TRACKING_RESULTS
REGISTER_MODEL_FOR_RANK_POINTS
GET_NUM_KILLS_FOR_RANK_POINTS
ScriptAny NETWORK_IS_PLAYER_TYPING(ScriptAny);
void SET_RICH_PRESENCE_TEMPLATEMP1(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny NETWORK_GET_UNACCEPTED_INVITER_NAME(ScriptAny);
void SET_RICH_PRESENCE_TEMPLATEMP4(ScriptAny, ScriptAny);
void NETWORK_GET_FIND_RESULT(ScriptAny, ScriptAny);
void TELL_NET_PLAYER_TO_START_PLAYING(ScriptAny, ScriptAny);
SET_INVINCIBILITY_TIMER_DURATION 
ScriptAny GET_CLOSEST_NETWORK_RESTART_NODE(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny GET_RANDOM_NETWORK_RESTART_NODE(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
GET_RANDOM_NETWORK_RESTART_NODE_OF_GROUP
GET_RANDOM_NETWORK_RESTART_NODE_EXCLUDING_GROUP
ScriptAny GET_RANDOM_NETWORK_RESTART_NODE_USING_GROUP_LIST(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
ScriptAny GET_SORTED_NETWORK_RESTART_NODE(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
GET_SORTED_NETWORK_RESTART_NODE_OF_GROUP
GET_SORTED_NETWORK_RESTART_NODE_EXCLUDING_GROUP
ScriptAny GET_SORTED_NETWORK_RESTART_NODE_USING_GROUP_LIST(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
CALCULATE_FURTHEST_NETWORK_RESTART_NODES
GET_FURTHEST_NETWORK_RESTART_NODE
void CLEAR_NETWORK_RESTART_NODE_GROUP_LIST(void);
void ADD_GROUP_TO_NETWORK_RESTART_NODE_GROUP_LIST(ScriptAny);
void FLUSH_ALL_PLAYER_RESPAWN_COORDS(void);
void ADD_SPAWN_BLOCKING_AREA(ScriptAny, ScriptAny, ScriptAny, ScriptAny);
void ADD_SPAWN_BLOCKING_DISC(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
void FLUSH_ALL_SPAWN_BLOCKING_AREAS(void);
void GET_COORDINATES_FOR_NETWORK_RESTART_NODE(ScriptAny, ScriptAny, ScriptAny);
void GET_SPAWN_COORDINATES_FOR_CAR_NODE(ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny, ScriptAny);
RESET_NETWORK_RESTART_NODE_GROUP_MAPPING
ADD_AREA_TO_NETWORK_RESTART_NODE_GROUP_MAPPING
ALLOW_NETWORK_POPULATION_GROUP_CYCLING